server.servlet.context-path: /api

gestore-catalogo:
    jwt:
        issuer: gestore-catalogo

spring:

    application:
        name: gestore-catalogo

    datasource:
        url: ${MYSQL_URL}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASS}